/**
 * @file include/communication_avoiding/gmres_ca_step.hpp
 * @brief Declares sequential CA-GMRES restart cycles.
 * @author Edward Curry
 * @date 2026-08-23
 * @details Last updated by Edward Curry on 2026-08-23.
 */

#ifndef COMMUNICATION_AVOIDING_GMRES_CA_STEP_HPP
#define COMMUNICATION_AVOIDING_GMRES_CA_STEP_HPP

#include "common/config.hpp"
#include "common/dense_block.hpp"
#include "common/sparse_matrix.hpp"
#include "common/types.hpp"
#include "communication_avoiding/ca_residual_history.hpp"

namespace gmres {

/**
 * @brief Carries a GMRES-DR deflation subspace between cycles.
 */
struct DeflationSubspace {
    /// @brief Orthonormal seed vectors with k plus one columns.
    DenseBlock V;
    /// @brief Arnoldi relation for the retained subspace.
    DenseMatrix Hbar;
    /// @brief Number of retained harmonic Ritz vectors.
    Index k = 0;
};

/**
 * @brief Stores the result of one sequential CA-GMRES cycle.
 */
struct CAGMRESCycleResult {
    Vector x;
    CAResidualHistory residual_history;
    Index blocks_completed = 0;
    Index iterations = 0;
    bool converged = false;

    /// @brief Deflation subspace prepared for the next cycle.
    DeflationSubspace next_deflation;

    /// @brief Leja-ordered Ritz shifts generated by a bootstrap cycle.
    Vector bootstrap_shifts;

    /// @brief Width to carry into the next adaptive cycle.
    Index adapted_s = 0;
};

/**
 * @brief Executes one non-deflated CA-GMRES restart cycle.
 * @param A System matrix.
 * @param b Right-hand side.
 * @param x_start Solution at cycle entry.
 * @param r_start Residual at cycle entry.
 * @param beta Norm of r_start.
 * @param initial_beta Initial residual norm for relative convergence.
 * @param config Solver configuration.
 * @param shifts Newton shifts, or an empty vector for bootstrap.
 * @param carried_s Width accepted by the preceding cycle.
 * @return Updated solution, residual history, and adaptive state.
 */
CAGMRESCycleResult gmres_ca_cycle(const SparseMatrixCSR& A,
                                  const Vector& b,
                                  const Vector& x_start,
                                  const Vector& r_start,
                                  Scalar beta,
                                  Scalar initial_beta,
                                  const GMRESConfig& config,
                                  const Vector& shifts = Vector(),
                                  Index carried_s = 0);

/**
 * @brief Executes one deflated CA-GMRES restart cycle.
 * @param A System matrix.
 * @param b Right-hand side.
 * @param x_start Solution at cycle entry.
 * @param r_start Residual at cycle entry.
 * @param beta Norm of r_start.
 * @param initial_beta Initial residual norm for relative convergence.
 * @param config Solver configuration.
 * @param deflation Retained subspace from the preceding cycle.
 * @param shifts Newton shifts, or an empty vector for bootstrap.
 * @param carried_s Width accepted by the preceding cycle.
 * @return Updated solution, residual history, and next deflation subspace.
 */
CAGMRESCycleResult gmres_ca_dr_cycle(const SparseMatrixCSR& A,
                                     const Vector& b,
                                     const Vector& x_start,
                                     const Vector& r_start,
                                     Scalar beta,
                                     Scalar initial_beta,
                                     const GMRESConfig& config,
                                     const DeflationSubspace& deflation =
                                         DeflationSubspace(),
                                     const Vector& shifts = Vector(),
                                     Index carried_s = 0);

}

#endif
